name: hilmi_berkay_ozdemir
description: A new Flutter web site project which contaion a lot high quality feature.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2


  # State Management
  # my own state management package for mvvm arcihtecture
  # https://pub.dev/packages/my_mvvm this is a stacked package fork but I solved some solution and add more clean dart code and several enchantments and more basic version
  my_mvvm: 0.0.2
  provider: ^6.0.4  
  
  #Design Language System
  dls:
    path: ./packages/dls


  #Network System
  network:
    path: ./packages/network
  dio: ^4.0.6

  #List and map filteration manipulators
  collection: ^1.16.0

  #navigator
  go_router: ^5.2.2


  #Testing 

 #logger
  logger: ^1.1.0
  layout: ^1.0.3
  responsive_builder: ^0.4.3
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  get_it: ^7.2.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/ 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
